name: tag

on:
  push:
    paths:
      - PetTracker.toc
    branches:
      - master

jobs:
  tag:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@master
      - uses: jaliborc/action-general-autotag@master
        with:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          source_file: "PetTracker.toc"
          extraction_regex: "\\s*##\\s*Version\\s*:\\s*([\\d\\.]+)"
